### ISSUE TITLE
maw-muter.exe is getting flagged by Windows Defender

### ISSUE THREAD

**Issue by MistaDjango** [tfurci/maw-muter#1] opened 2023-11-10 14:58 UTC
That's basically it. Program is getting flagged by Windows Defender.

**Comment by tfourj** [comment] 2023-11-11 14:43
Thanks for reporting the issue, does it get flagged as virus or unwanted application, also does it get flagged on donwload or when you run it(left clicking the .exe or thru cmd?)

**Comment by MistaDjango** [comment] 2023-11-11 22:12
It happens on download, its flagged as a virus.

**Comment by tfourj** [comment] 2023-11-18 21:05
~~Is the same happening with new v2.0.0 release, as i sent the .exe to microsoft and they analized it without reproducing the issue~~

EDIT: I think i found the issue and should hopefully be fixed in v3.0.0 release soon, most of the flags at virus-total was because of CosturaFody to pack a file into 1 exe now i moved to native .NET framework and should hopefully fix the flags. let me know if it still gets flagged (v3.0.0)

**Closed as completed** 2023-12-15 12:43 UTC
